### ISSUE TITLE
vscode-angular-html scope changes

### ISSUE THREAD

**Issue by ghaschel** [gitchaell/angular-vscode-theme#3]
Not really a enhancement request. But just a FYI. I updated vscode-angular-html, and it now doesn't use all the previously matches scopes. It uses different ones, and has a feature that allows you to customize the desired colors as you want, or set the legacy colors. I have documented every scope change [here](https://github.com/ghaschel/vscode-angular-html/blob/master/docs/THEMING.md).

I will regardless of that, I'll add support for your themes via the `Set Legacy Colors customizations` command. Thanks for supporting my extension :)

**Comment by gitchaell** [comment]
Thank you for the information. Having better structured and identified code tokens has helped me to be able to customize the angular theme much more accurately, and finally help developers to differentiate their lines of code more easily.

Good job!

The changes made accordingly can be reviewed in [v5.0.0](https://github.com/gitchaell/angular-vscode-theme/commit/19077967443487ece57e11c30f72670704d25b2e#diff-d1d310b3dea5300fa02920406ddfe85146b36e9ac22076834b74f3d7356f6163)

**Comment by ghaschel** [comment]
Glad to hear it was helpful. Anytime.
